### ISSUE TITLE
typing_extensions issue

### ISSUE THREAD

**Issue by Khyati-Microcrispr** [ncbi/AIONER#2]
**Hi, I followed this set up** 
conda create -n tf2.3 python=3.7
conda activate tf2.3
conda install -c conda-forge cudatoolkit=10.1 cudnn=7.6
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
**then installed the requirements sucessfully but while running AIONER, I am getting this error. Please help resolving this issue as soon as possible. Thank you for this advance tool**

AIONER-main$ python src/AIONER_Run.py -i ../example/input/ -m ../pretrained_models/AIONER/Bioformer-softmax-AIONER.h5 -v ../vocab/AIO_label.vocab -e ALL -o ../example/output/
2024-05-31 16:20:56.266464: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2024-05-31 16:20:58.052726: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcuda.so.1
2024-05-31 16:20:58.093898: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1716] Found device 0 with properties: 
pciBusID: 0000:31:00.0 name: NVIDIA GeForce RTX 4090 computeCapability: 8.9
coreClock: 2.52GHz coreCount: 128 deviceMemorySize: 23.64GiB deviceMemoryBandwidth: 938.86GiB/s
2024-05-31 16:20:58.093962: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1
2024-05-31 16:20:58.096369: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcublas.so.10
2024-05-31 16:20:58.098784: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcufft.so.10
2024-05-31 16:20:58.099218: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcurand.so.10
2024-05-31 16:20:58.101683: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusolver.so.10
2024-05-31 16:20:58.102992: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcusparse.so.10
2024-05-31 16:20:58.108054: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudnn.so.7
2024-05-31 16:20:58.108705: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1858] Adding visible gpu devices: 0
Num GPUs Available:  1
Traceback (most recent call last):
  File "src/AIONER_Run.py", line 27, in <module>
    import stanza
  File "/home/khyati/anaconda3/envs/tf2.3/lib/python3.7/site-packages/stanza/__init__.py", line 1, in <module>
    from stanza.pipeline.core import Pipeline
  File "/home/khyati/anaconda3/envs/tf2.3/lib/python3.7/site-packages/stanza/pipeline/core.py", line 20, in <module>
    from stanza.pipeline.langid_processor import LangIDProcessor
  File "/home/khyati/anaconda3/envs/tf2.3/lib/python3.7/site-packages/stanza/pipeline/langid_processor.py", line 5, in <module>
    import emoji
  File "/home/khyati/anaconda3/envs/tf2.3/lib/python3.7/site-packages/emoji/__init__.py", line 47, in <module>
    from emoji.core import *
  File "/home/khyati/anaconda3/envs/tf2.3/lib/python3.7/site-packages/emoji/core.py", line 12, in <module>
    from typing_extensions import Literal, Match, TypedDict
ImportError: cannot import name 'Match' from 'typing_extensions' (/home/khyati/anaconda3/envs/tf2.3/lib/python3.7/site-packages/typing_extensions.py)

**Comment by Khyati-Microcrispr** [comment]
/ @ Po-Ting Lai

**Comment by lingluodlut** [comment]
Hi, this issue is likely due to an incompatibility between the versions of the emoji and typing_extensions libraries installed in your environment, but not AIONER. Could you list the versions of the libraries in your environment?

**Comment by Khyati-Microcrispr** [comment]
python = 3.7 
absl-py==2.1.0
AmberUtils==21.0
astunparse==1.6.3
attrs==24.2.0
backcall==0.2.0
bioc==2.0.post4
blis==0.7.11
cachetools==5.5.0
catalogue==2.0.10
certifi @ file:///croot/certifi_1671487769961/work/certifi
charset-normalizer==3.4.0
click==8.0.4
cycler==0.11.0
cymem==2.0.8
debugpy==1.7.0
decorator==5.1.1
edgembar==3.0
emoji==2.12.0
entrypoints==0.4
filelock==3.12.2
flatbuffers==24.3.25
fonttools==4.38.0
fsspec==2023.1.0
gast==0.3.3
google-auth==2.36.0
google-auth-oauthlib==0.4.6
google-pasta==0.2.0
grpcio==1.62.3
h5py==2.10.0
huggingface-hub==0.16.4
idna==3.10
importlib-metadata==6.7.0
intervaltree==3.1.0
ipykernel==6.16.2
ipython==7.34.0
jedi==0.19.2
Jinja2==3.1.4
joblib==1.3.2
jsonlines==3.1.0
jupyter_client==7.4.9
jupyter_core==4.12.0
keras==2.11.0
Keras-Preprocessing==1.1.2
kiwisolver==1.4.5
langcodes==3.3.0
libclang==18.1.1
lxml==5.3.0
Markdown==3.4.4
MarkupSafe==2.1.5
matplotlib==3.5.3
matplotlib-inline==0.1.6
MMPBSA.py==16.0
murmurhash==1.0.10
ndfes==3.0
nest-asyncio==1.6.0
numpy==1.21.6
nvidia-cublas-cu11==11.10.3.66
nvidia-cuda-nvrtc-cu11==11.7.99
nvidia-cuda-runtime-cu11==11.7.99
nvidia-cudnn-cu11==8.5.0.96
oauthlib==3.2.2
opt-einsum==3.3.0
packaging==24.0
packmol_memgen==2024.3.27
pandas==1.3.5
ParmEd==0+unknown
parso==0.8.4
pathy==0.10.3
pdb4amber==22.0
pexpect==4.9.0
pickleshare==0.7.5
Pillow==9.5.0
preshed==3.0.9
prompt_toolkit==3.0.48
protobuf==3.19.6
psutil==6.1.0
ptyprocess==0.7.0
pyasn1==0.5.1
pyasn1-modules==0.3.0
pydantic==1.8.2
Pygments==2.17.2
pyMSMT==22.0
pyparsing==3.1.4
python-dateutil==2.9.0.post0
pytraj==2.0.6
pytz==2024.2
PyYAML==6.0.1
pyzmq==26.2.0
regex==2024.4.16
requests==2.31.0
requests-oauthlib==2.0.0
rsa==4.9
sacremoses==0.0.53
sander==22.0
scipy==1.4.1
six==1.16.0
smart-open==6.4.0
sortedcontainers==2.4.0
spacy==3.2.4
spacy-legacy==3.0.12
spacy-loggers==1.0.5
srsly==2.4.8
stanza==1.4.0
tensorboard==2.11.2
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
tensorflow==2.11.0
tensorflow-addons==0.12.1
tensorflow-estimator==2.11.0
tensorflow-io-gcs-filesystem==0.34.0
termcolor==2.3.0
thinc==8.0.17
tokenizers==0.12.1
torch==1.13.1
tornado==6.2
tqdm==4.67.0
traitlets==5.9.0
transformers==4.18.0
typeguard==2.13.3
typer==0.4.2
typing-extensions==3.7.4.3
urllib3==2.0.7
wasabi==0.10.1
wcwidth==0.2.13
Werkzeug==2.2.3
wrapt==1.16.0
zipp==3.15.0

**Comment by Khyati-Microcrispr** [comment]
please help, I have sent the library versions in my envionment, can you tell me cuda and cudnn versions?

**Comment by Khyati-Microcrispr** [comment]
Hi,  as AIONER does on provide the indentifier linking, could you suggest a way which have automated entity linking for non publications data ( not having pubmedids) ?

**Comment by alejoaa** [comment]
I was facing the same issue and solved it by running `pip install --upgrade emoji`. I was able to run AIONER with the following package versions:
- `emoji 2.14.1`
- `stanza 1.4.0`
- `typing_extensions 4.7.1`

Hope this helps!
